keys:
  - &heartblin age17psv7ck3clmdjcapyftpx6relxcselpy9pcf42wdrrklhnrldy0sgf8nju
  - &Reason age18xa5sx3g76z7u5x62k55sjedmgfc66n43zxx0l4y4nxxka5d4yhq6nhdmz

creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
      - age:
        - *heartblin
        - *Reason
