import re
import textwrap
from dataclasses import dataclass
from .logging import LOGI, LOGO, LOGE

# He was whipping up CFGs in a kettle
# Actual CFGs?
# Actual CFGs. And CPIOs.
@dataclass
class NixOSEntry:
    linux_dir: str
    init_dir: str
    initrd_dir: str

def get_store_path_matrix(text):
    # BTW: Fun Fact. Official NixOS images have 4 entries
    # GNOME + LTS, GNOME + Latest, KDE + LTS, KDE + Latest
    # I only have one.
    menuentry_regex = r"menuentry\s+['\"][^'\"]+['\"].*?\{\n(.*?)^\}"

    for block_body in re.findall(menuentry_regex, text, re.DOTALL | re.MULTILINE):
        linux_match = re.search(r"linux\s+/boot/?/nix/store/([^/\s]+)/bzImage", block_body)
        init_match = re.search(r"init=/nix/store/([^/\s]+)/init", block_body)
        initrd_match = re.search(r"initrd\s+/boot/?/nix/store/([^/\s]+)/initrd", block_body)

        if linux_match and init_match and initrd_match:
            entry = NixOSEntry(
                linux_dir=linux_match.group(1),
                init_dir=init_match.group(1),
                initrd_dir=initrd_match.group(1)
            )
            LOGO("get_store_path_matrix", "Got NixOS menuentry")
            return entry

    LOGE("get_store_path_matrix", "No valid menuentry found")
    return None

def build_inc_cfg(entry, iso, iso_dir):
    cfg_name = f"inc-{iso_dir}.cfg"
    LOGI("build_inc_cfg", f"Building '{cfg_name}'...")

    with open(cfg_name, "w") as file:
        file.write("# Generated by patch-Origin-Finality\n")
        file.write(f"# Target ISO: {iso}\n\n")
        file.write(make_menuentry(entry, iso, iso_dir))

    LOGO("build_inc_cfg", f"Built {cfg_name}")


def make_menuentry(entry, iso, iso_dir):
    iso_stem = iso.rsplit(".", 1)[0]
    args = "elevator=noop nohibernate root=fstab splash loglevel=4 lsm=landlock,yama,bpf copytoram"

    return textwrap.dedent(f"""\
        menuentry "{iso_dir}" --class nixos {{
            set isofile="/boot/iso/{iso_dir}/{iso}"
            loopback loop $isofile
            terminal_output console
            linux (loop)/boot/nix/store/{entry.linux_dir}/bzImage init=/nix/store/{entry.init_dir}/init {args}
            initrd (loop)/boot/nix/store/{entry.initrd_dir}/initrd /boot/iso/{iso_dir}/{iso_stem}-loop-patch.cpio
        }}
    """)
