name: Cache Warming

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - flake.lock
      - 'packages/alejandra-custom/adblock.patch'
      - 'packages/alejandra-custom/default.nix'
      - 'packages/alejandra-custom/style.patch'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 2

      - uses: cachix/install-nix-action@v31
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            experimental-features = nix-command flakes pipe-operators

      - uses: cachix/cachix-action@v17
        with:
          name: 1nfr4
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build packages
        run: nix build .#alejandra-custom
